name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: yasminalves16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=d63384&color_dots=%23fde2e4,%23f8c8dc,%23f4a9c2,%23e685a1,%23d63384

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
