name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: yasminalves16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=E6A4B4&color_dots=%23f8d7da,%23f4b6c2,%23eea5b7,%23E6A4B4,%23d98fa6

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
